### ISSUE TITLE
what does the argument "ds" means? 

### ISSUE THREAD

**Issue by lc82111** [317070/Twitch-plays-LSD-neural-net#2]
In default_image.py: 

```
max_pool = partial(dnn.MaxPool2DDNNLayer,
                            ds=(2,2), 
                           strides=(2,2))
```

I found ds param, however I can't find this in lasagne documents.

BTW, I encounter out of memory error: 'Error allocating X bytes of device memory (out of memory).' Is  this caused by my insufficient RAM? My computer equipped with 2GB RAM and a 4GB GPU.

**Comment by 317070** [comment]
ds is pool_size in the latest version of lasagne.

> BTW, I encounter out of memory error: 'Error allocating X bytes of device memory (out of memory).' Is this caused by my insufficient RAM? My computer equipped with 2GB RAM and a 4GB GPU.

Yes, I'm afraid so :-/
On our machines, we use constantly 3.9GB of GPU RAM and 12GB of CPU RAM. With peaks going up higher. So The GPU is OK, but you'll need more ram on the CPU to buffer the frames. However, I think you should be able to run train_image.py and generate images.
