### ISSUE TITLE
VLFeat hosted mat files changed format

### ISSUE THREAD

**Issue by bluemellophone** [317070/Twitch-plays-LSD-neural-net#4]
The format of the VGG network model files has changed and the mat2npy.py processing file no longer works with the new format.

What is the original shapes of data/vgg16.npy, data/mean-16.npy, and data/classes-16.npy?  I attempted to reprocess the new format and below is the shapes I get for the various Numpy arrays.  I want to know if this is consistent with the old format before I debug any further.

```
Verified 'imagenet-vgg-verydeep-16.mat' (md5 = f72d927587ca4c97fbd165ec9cb9997f)
Verified 'imagenet-vgg-verydeep-19.mat' (md5 = 106118b7cf60435e6d8e04f6a6dc3657)

Processing: 16
['layers', '__version__', 'meta', '__header__', '__globals__']
Params:
     (64, 3, 3, 3) (64, 1)
     (64, 64, 3, 3) (64, 1)
     (128, 64, 3, 3) (128, 1)
     (128, 128, 3, 3) (128, 1)
     (256, 128, 3, 3) (256, 1)
     (256, 256, 3, 3) (256, 1)
     (256, 256, 3, 3) (256, 1)
     (512, 256, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (4096, 512, 7, 7) (4096, 1)
     (4096, 4096, 1, 1) (4096, 1)
     (1000, 4096, 1, 1) (1000, 1)
Mean:
     (1, 3)
Classes:
     (1000,)

Processing: 19
['layers', '__version__', 'meta', '__header__', '__globals__']
Params:
     (64, 3, 3, 3) (64, 1)
     (64, 64, 3, 3) (64, 1)
     (128, 64, 3, 3) (128, 1)
     (128, 128, 3, 3) (128, 1)
     (256, 128, 3, 3) (256, 1)
     (256, 256, 3, 3) (256, 1)
     (256, 256, 3, 3) (256, 1)
     (256, 256, 3, 3) (256, 1)
     (512, 256, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (512, 512, 3, 3) (512, 1)
     (4096, 512, 7, 7) (4096, 1)
     (4096, 4096, 1, 1) (4096, 1)
     (1000, 4096, 1, 1) (1000, 1)
Mean:
     (1, 3)
Classes:
     (1000,)
```

Alternatively, would you be willing to provide a mirror for the old model files?

**Comment by 317070** [comment]
```
['layers', '__header__', '__globals__', 'classes', '__version__', 'normalization']
(64, 3, 3, 3) (64,)
(64, 64, 3, 3) (64,)
(128, 64, 3, 3) (128,)
(128, 128, 3, 3) (128,)
(256, 128, 3, 3) (256,)
(256, 256, 3, 3) (256,)
(256, 256, 3, 3) (256,)
(512, 256, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(4096, 512, 7, 7) (4096,)
(4096, 4096, 1, 1) (4096,)
(1000, 4096, 1, 1) (1000,)
['layers', '__header__', '__globals__', 'classes', '__version__', 'normalization']
(64, 3, 3, 3) (64,)
(64, 64, 3, 3) (64,)
(128, 64, 3, 3) (128,)
(128, 128, 3, 3) (128,)
(256, 128, 3, 3) (256,)
(256, 256, 3, 3) (256,)
(256, 256, 3, 3) (256,)
(256, 256, 3, 3) (256,)
(512, 256, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(512, 512, 3, 3) (512,)
(4096, 512, 7, 7) (4096,)
(4096, 4096, 1, 1) (4096,)
(1000, 4096, 1, 1) (1000,)

```

**Comment by bluemellophone** [comment]
Thank you.

Can you also verify the shapes of the mean and classes Numpy arrays?  The one I have been most worried about was the mean.  I think I get an RGB (or BGR) mean pixel value instead of a mean image.

**Comment by 317070** [comment]
OK, I find

```
(224, 224, 3)
(1000,)

```

I guess the mean is calculated per pixel. (Why would anyone want to do it like that?)
So mean image it is/was.

**Comment by bluemellophone** [comment]
Yes, a per-pixel mean image is what usually gets distributed.  This is what OverFeat used way back when.  I'm actually kind of glad the practice of a mean image (or mean channel value) has gone out of fashion to at least some degree.

**Edit:** the theory behind doing an actual mean image across the entire dataset would be that there may be some underlying distribution about the inherent sampling of images taken by humans.  For example, humans tend to put the most prominent and well-composed objects in the center of the image.  The theory being that the distribution of image data in the middle of the image would be slightly different (on average) than say the corners.  Imaging like a distribution vignetting... but long story short, this practice has basically died in the latest CNNs because the assumptions are too rigid and it has always been a bit of a pain in the ass to compute and maintain this mean image on a large dataset.

However, according to (at least) [this discussion](https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3#gistcomment-1616734) the VGG uses a per-channel mean value instead.  The values that are loaded out of the newly formatted mat file (123.68, 116.779, 103.939) are the same as provided in that discussion.  I would expect the version you have in the old mat file format is just a broadcast of this mean channel pixel across an image of shape (224, 224, 3).  I would expect each channel of that image to be homogeneous with respect to itself.

Thank you again for verifying these values and the data shapes.
